<?php
if (!defined('BASEPATH')) exit('No direct script access allowed');

$this->load->view('inventori/lokasi_per_barang');
$this->load->view('inventori/barang_per_bulan_per');
$this->load->view('inventori/minimum_stok');
$this->load->view('inventori/stok_barang_bonus');
$this->load->view('inventori/mutasi_barang');
$this->load->view('inventori/stok_opname');
$this->load->view('inventori/setting_stock_produk');
$this->load->view('inventori/approval_setting_stock_produk');
$this->load->view('inventori/approval_setting_stock_produkb');
$this->load->view('inventori/barterbarang');
$this->load->view('inventori/barter_approval_ops');
$this->load->view('inventori/barter_approval_buyer');
$this->load->view('inventori/barter_surat_kirim');
$this->load->view('inventori/barter_surat_kembali');
$this->load->view('inventori/stokopname_initial');
$this->load->view('inventori/stokopname_entry');
$this->load->view('inventori/stokopname_approval');
$this->load->view('inventori/mutasi_lokasi_out');
$this->load->view('inventori/mutasi_in');
$this->load->view('inventori/in_out_stok');
$this->load->view('inventori/outstanding_mutasi');
$this->load->view('inventori/view_mutasi');
$this->load->view('inventori/print_mutasi');
$this->load->view('inventori/cetak_barter_barang');
$this->load->view('inventori/monitoring_barter_barang');
$this->load->view('inventori/cetak_in_out_stok');
$this->load->view('inventori/input_barang_pecah');
?>